@PORT = 3000
@endpoint = http://localhost:{{PORT}}/api/v1/products

GET {{endpoint}}

###

POST {{endpoint}}/add-product
Content-Type: application/json

{
    "name" : "chowmein",
    "price" : 23,
    "rating" : 4.5,
    "img": "random url",
    "description": "food by ram"
}

###
DELETE {{endpoint}}/delete/6798a5da3790de2192be3381

###
PUT {{endpoint}}/update/6798a84afe21abc1c78faa31
Content-Type: application/json

{
    "name" : "momo",
    "price" : 24,
    "rating" : 5,
}

